[package]
name = "vis-diff"
version = "0.1.0"
authors = ["David Barsky <me@davidbarsky.com>"]

[dependencies]
difference = "1.0"
failure = "0.1.1"
failure_derive = "0.1.1"
structopt = "0.1.0"
structopt-derive = "0.1.0"